CREATE TABLE `T_OFFICES` (
`OFFC_ID` INT NOT NULL,
`OFFC_COUNTRY` VARCHAR(30) NOT NULL,
`OFFC_DESCRIPTION` VARCHAR(80) NOT NULL,
`OFFC_NAME` VARCHAR(30)
);

-- DROP TABLE T_OFFICES; --

CREATE TABLE T_OFFICES (
OFFC_ID INT NOT NULL,
OFFC_COUNTRY VARCHAR(30) NOT NULL,
OFFC_DESCRIPTION VARCHAR(90) NOT NULL,
OFFC_NAME VARCHAR(30)
);

ALTER TABLE T_OFFICES
DROP COLUMN OFFC_CITY;

ALTER TABLE T_OFFICES
ADD COLUMN 
	OFFC_CITY VARCHAR(50) NOT NULL
    AFTER OFFC_COUNTRY;
    
ALTER TABLE T_OFFICES
CHANGE COLUMN OFFC_DESCRIPTION
	OFFC_DESCRIPTION VARCHAR(100);
    
DESC T_OFFICES;

ALTER TABLE T_OFFICES
DROP COLUMN OFFC_NAME;

use db_empl;

DROP TABLE T_OFFICES;


