INSERT INTO T_OFFICES
(
	OFFC_ID, OFFC_COUNTRY, OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
	10, 'España', 'Madrid', 'Oficina central'
);

INSERT INTO T_OFFICES
(
	OFFC_ID, OFFC_COUNTRY, OFFC_CITY
)
VALUES
(
	11, 'España', 'Barcelona'
);

INSERT INTO T_OFFICES
(
	OFFC_ID, OFFC_COUNTRY, OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
	20, 'Chile', 'Santiago', 'Oficina principal de Chile'
),
(
	30, 'Argentina', 'Buenos aires', NULL
);

SELECT * FROM T_OFFICES
	WHERE OFFC_ID = 30;
    
UPDATE T_OFFICES
	SET OFFC_CITY = 'Buenos Aires'
    WHERE OFFC_ID = 30;
    
SELECT OFFC_ID, OFFC_COUNTRY, OFFC_CITY FROM T_OFFICES
	WHERE OFFC_DESCRIPTION LIKE 'Oficina%'

SELECT * FROM T_OFFICES;

CREATE TABLE T_KNOWLEDGE_LINES (
KNLN_ID INT(11) NOT NULL,
KNLN_NAME VARCHAR(45) NOT NULL,
PRIMARY KEY (KNLN_ID)
);

DESC T_KNOWLEDGE_LINES;

INSERT INTO T_KNOWLEDGE_LINES (KNLN_ID, KNLN_NAME)
VALUES (10, 'Java'), (20, '.NET'), (30, 'Mainframe');

SELECT * FROM T_KNOWLEDGE_LINES;
