SELECT e.EMPL_FORNAME, e.EMPL_SURNAME, o.OFFC_CITY, k.KNLN_NAME
FROM T_EMPLOYEES e
INNER JOIN T_OFFICES o ON
	e.OFFC_ID = o.OFFC_ID
LEFT OUTER JOIN T_KNOWLEDGE_LINES k ON
	e.KNLN_ID = k.KNLN_ID
WHERE o.OFFC_COUNTRY IN ('España', 'Chile')
AND e.EMPL_MENTOR_ID is NULL

SELECT p.PRJT_CODE, p.PRJT_NAME, e.EMPL_NUMBER, e.EMPL_SURNAME
FROM t_projects p
INNER JOIN t_projects_employees pe
	ON p.PRJT_ID = pe.PRJT_ID
INNER JOIN t_employees e
	ON e.EMPL_ID = pe.EMPL_ID
WHERE e.EMPL_FORNAME = 'Juan'

