CREATE DATABASE mecanico;

use mecanico;

CREATE TABLE PROVEEDORES(
	PROV_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_NOM VARCHAR(50) NOT NULL,
	PRIMARY KEY (PROV_ID)
);

CREATE TABLE PIEZAS(
	PIEZ_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PIEZ_NOM VARCHAR(100) NOT NULL,
	PRIMARY KEY (PIEZ_ID)
);

CREATE TABLE PRECIOS(
	PREC_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_ID INT UNSIGNED NOT NULL,
	PIEZ_ID INT UNSIGNED NOT NULL,
    PRECIO DECIMAL(10, 2) UNSIGNED DEFAULT NULL,
	PRIMARY KEY (PREC_ID)
);

ALTER TABLE PRECIOS
	ADD INDEX FK_PREC_PROV (PROV_ID),
    ADD CONSTRAINT FK_PREC_PROV
		FOREIGN KEY (PROV_ID)
        REFERENCES PROVEEDORES (PROV_ID);

ALTER TABLE PRECIOS
	ADD INDEX FK_PREC_PIEZ (PIEZ_ID),
    ADD CONSTRAINT FK_PREC_PIEZ
		FOREIGN KEY (PIEZ_ID)
        REFERENCES PIEZAS (PIEZ_ID);
        
ALTER TABLE PRECIOS
	ADD CONSTRAINT CT_UQ_PROV_PIEZ_ID
    UNIQUE(PROV_ID, PIEZ_ID);
    
SELECT PIEZ_NOM FROM PIEZAS;
			
SELECT * FROM PROVEEDORES;

SELECT AVG(PRECIO) AS PRECIO_MEDIO FROM PRECIOS;

SELECT PIEZ_ID, AVG(PRECIO) AS PRECIO_MEDIO 
FROM PRECIOS
GROUP BY PIEZ_ID;

-- Valor medio de precios agrupado por piezas
SELECT pi.PIEZ_ID, pi.PIEZ_NOM, AVG(pr.PRECIO) AS PRECIO_MEDIO 
FROM PRECIOS pr
INNER JOIN PIEZAS pi
ON pr.PIEZ_ID = pi.PIEZ_ID
GROUP BY pr.PIEZ_ID;

-- Valor medio de precios agrupado por proveedor
SELECT pro.PROV_ID, pro.PROV_NOM, AVG(pre.PRECIO) AS PRECIO_MEDIO 
FROM PRECIOS pre
INNER JOIN PROVEEDORES pro
ON pre.PROV_ID = pro.PROV_ID
GROUP BY pre.PROV_ID;

SELECT DISTINCT pro.PROV_NOM
FROM PROVEEDORES pro
INNER JOIN PRECIOS pre
ON pro.PROV_ID = pre.PROV_ID 
WHERE pre.PIEZ_ID = 3;

SELECT PROV_NOM
FROM PROVEEDORES
WHERE PROV_ID IN
(SELECT PROV_ID FROM PRECIOS WHERE PIEZ_ID = 3);

SELECT pi.PIEZ_NOM
FROM PIEZAS pi
INNER JOIN PRECIOS pr
ON pi.PIEZ_ID = pr.PIEZ_ID
WHERE pr.PROV_ID = 2;

SELECT pi.PIEZ_NOM
FROM PIEZAS pi
INNER JOIN PRECIOS pr
ON pi.PIEZ_ID = pr.PIEZ_ID
INNER JOIN PROVEEDORES pro
ON pr.PROV_ID = pro.PROV_ID
WHERE pro.PROV_NOM = 'NISSAN';

SELECT pz.PIEZ_NOM, pro.PROV_NOM, pz.PIEZ_ID, MAX(pr.PRECIO) AS PRECIO_MAXIMO
FROM PIEZAS pz
INNER JOIN PRECIOS pr
ON pz.PIEZ_ID = pr.PIEZ_ID
INNER JOIN PROVEEDORES pro
ON pr.PROV_ID = pro.PROV_ID
GROUP BY pz.PIEZ_ID;

SELECT * FROM PRECIOS;

UPDATE PRECIOS
SET PRECIO = PRECIO + 1;

DELETE
FROM PRECIOS
WHERE PROV_ID = 9
AND PIEZ_ID = 4;







