use tienda;

ALTER TABLE ARTICULOS
CHANGE COLUMN FAB_ID 
FAB_ID INT(10) NOT NULL;

ALTER TABLE ARTICULOS
ADD INDEX FK_ART_FAB (FAB_ID),
ADD CONSTRAINT FK_ART_FAB
FOREIGN KEY (FAB_ID)
REFERENCES FABRICANTES (FAB_ID);

SELECT ART_NOM FROM articulos;

SELECT ART_NOM, ART_PRECIO FROM articulos;

SELECT ART_NOM, ART_PRECIO FROM articulos
WHERE ART_PRECIO >= 200;

SELECT ART_NOM, ART_PRECIO FROM articulos
WHERE ART_PRECIO BETWEEN 10 AND 50;
-- WHERE ART_PRECIO >= 10 AND ART_PRECIO <= 50;

-- FORMAT(Minutes/60.0, 'N2')
SELECT ART_NOM, ROUND(ART_PRECIO * 166.386, 2) AS PRECIO_PESETAS
FROM articulos;

SELECT ROUND(AVG(ART_PRECIO), 2) AS PRECIO_MEDIO
FROM articulos;

SELECT ROUND(AVG(ART_PRECIO), 2) AS PRECIO_MEDIO
FROM articulos
WHERE FAB_ID = 2;

SELECT COUNT(ART_ID) AS NUM_ARTICULOS
FROM articulos
WHERE ART_PRECIO >= 180;

SELECT ART_NOM, ART_PRECIO 
FROM articulos
WHERE ART_PRECIO > 180
ORDER BY ART_PRECIO DESC;

SELECT ART_NOM, ART_PRECIO 
FROM articulos
WHERE ART_PRECIO > 180
ORDER BY ART_PRECIO ASC;

SELECT *
FROM articulos a
INNER JOIN fabricantes f
ON a.FAB_ID = f.FAB_ID;

SELECT a.ART_NOM, a.ART_PRECIO, f.FAB_NOM
FROM articulos a
INNER JOIN fabricantes f
ON a.FAB_ID = f.FAB_ID;

SELECT FAB_ID, AVG(ART_PRECIO) AS PRECIO_MEDIO
FROM articulos
-- INNER JOIN fabricantes f
-- ON a.FAB_ID = f.FAB_ID
GROUP BY FAB_ID;

SELECT f.FAB_NOM, AVG(a.ART_PRECIO) AS PRECIO_MEDIO
FROM articulos a
INNER JOIN fabricantes f
ON a.FAB_ID = f.FAB_ID
GROUP BY f.FAB_ID;

SELECT f.FAB_NOM, AVG(a.ART_PRECIO) AS PRECIO_MEDIO
FROM articulos a
INNER JOIN fabricantes f
ON a.FAB_ID = f.FAB_ID
GROUP BY f.FAB_ID
HAVING PRECIO_MEDIO >= 150;

SELECT ART_NOM, MIN(ART_PRECIO)
FROM articulos;

SELECT f.FAB_NOM, a.ART_NOM, MAX(a.ART_PRECIO) AS PRECIO_MAXIMO
FROM fabricantes f
INNER JOIN articulos a
ON a.FAB_ID = f.FAB_ID
GROUP BY f.FAB_ID;

INSERT INTO articulos
(
	ART_NOM, ART_PRECIO, FAB_ID
)
VALUES
(
	'Altavoces', 70, 2
);

UPDATE articulos
SET ART_NOM = 'Impresora Laser'
WHERE ART_ID = 8;

use tienda;

UPDATE articulos
SET ART_PRECIO = ART_PRECIO*0.9
WHERE ART_PRECIO >= 120;

SELECT ART_NOM, ART_PRECIO
FROM articulos;














